services:
  database:
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=somesecurepassword 
      - MONGO_INITDB_ROOT_USERNAME=somesecureusername
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
version: "3.8"
volumes:
  mongodata: