version: '3.1'
services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo:latest
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db